### ISSUE TITLE
Add support for CleanStart=false and Session Expiry Interval

### ISSUE THREAD

**Issue by andriiff** [eclipse/paho.golang#113] opened 2023-01-13 14:48 UTC
**Is your feature request related to a problem? Please describe.**
CleanStart is a core feature of MQTT protocol. It enables:
* automatically resubscribing client upon reconnect
* receiving QoS 1&2 messages missed while disconnected

**Describe the solution you'd like**
I would like to have a `CleanSession` flag configurable via client config. It is currently hardcoded to `true`.

**Describe alternatives you've considered**
Resubscribing manually upon reconnect. This only solves part of the problem though.

**Additional context**

**Comment by MattBrittan** [comment] 2023-01-13 21:00
Duplicate of issue #25 (persistence needs to be implemented in order to support `CleanStart=false`). This is not a trivial change; I have been meaning to have a go for a couple of years but have not got around to it (implementing basic persistence is not all that tricky but implementing it in a way that does not introduce too much complexity is more difficult).

**Comment by MattBrittan** [comment] 2023-10-05 09:16
I'm going to close this as a duplicate of #25 - support has been implemented in my test repo (see link in that issue) and I am currently testing it. Assistance with testing would be welcomed :-).

**Closed by MattBrittan** 2023-10-05 09:16 UTC
